// <auto-generated />
namespace Seaman.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddCryobank : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCryobank));
        
        string IMigrationMetadata.Id
        {
            get { return "201511270456064_AddCryobank"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
