// <auto-generated />
namespace Seaman.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _03_10_2015_00 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_03_10_2015_00));
        
        string IMigrationMetadata.Id
        {
            get { return "201510031027228_03_10_2015_00"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
